language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
env:
  - DB=postgres

before_script:
  - psql -c 'create database test_db;' -U postgres

script: 
  - nosetests --with-coverage
  - coveralls

after_success:
 - coveralls